
$modelname "weapons\arccw\atts\uc_urbancharm.mdl"

$body urbancharm "uc_urbancharm.smd"
$cdmaterials "models\weapons\arccw\atts\uc_urbancharm\"
$surfaceprop "combine_metal"
$staticprop

$texturegroup "skinfamilies"
{
	{ "uc_urbancharm_gray"      }
	{ "uc_urbancharm_ud"	    }
	{ "uc_urbancharm_ur"	    }
	{ "uc_urbancharm_ua"	    }
	{ "uc_urbancharm_uo"	    }
}

$sequence "idle" "uc_urbancharm.smd" loop fps 30